# สีลกฺขนฺธวคฺคปาฬิ {#ds}

## พฺรหฺมชาลสุตฺตํ

### ปริพฺพาชกกถา
เพิ่มเติมข้อความ
เอวมฺเม สุตํ ฯ เอกํ สมยํ ภควา อนฺตรา จ ราชคหํ อนฺตรา จ นาฬนฺทํ อทฺธานมคฺคปฏิปนฺโน โหติ มหตา ภิกฺขุสํเฆน สทฺธึ ปญฺจมตฺเตหิ ภิกฺขุสเตหิ ฯ สุปฺปิโยปิ โข ปริพฺพาชโก อนฺตรา จ ราชคหํ อนฺตรา จ นาฬนฺทํ อทฺธานมคฺคปฏิปนฺโน โหติ สทฺธึ อนฺเตวาสินา พฺรหฺมทตฺเตน มาณเวน ฯ ตตฺร สุทํ สุปฺปิโย ปริพฺพาชโก อเนกปริยาเยน พุทฺธสฺส อวณฺณํ ภาสติ ธมฺมสฺส อวณฺณํ ภาสติ สํฆสฺส อวณฺณํ ภาสติ ฯ สุปฺปิยสฺส ปน ปริพฺพาชกสฺส อนฺเตวาสี พฺรหฺมทตฺโต มาณโว อเนกปริยาเยน พุทฺธสฺส วณฺณํ ภาสติ ธมฺมสฺส วณฺณํ ภาสติ สํฆสฺส วณฺณํ ภาสติ ฯ อิติห เต อุโภ อาจริยนฺเตวาสี อญฺญมญฺญสฺส อุชุวิปจฺจนิกวาทา  ภควนฺตํ ปิฏฺฐิโต ปิฏฺฐิโต อนุพนฺธา โหนฺติ ภิกฺขุสํฆญฺจ ฯ

### สีล
เอวมฺเม สุตํ ฯ เอกํ สมยํ ภควา อนฺตรา จ ราชคหํ อนฺตรา จ นาฬนฺทํ อทฺธานมคฺคปฏิปนฺโน โหติ มหตา ภิกฺขุสํเฆน สทฺธึ ปญฺจมตฺเตหิ ภิกฺขุสเตหิ ฯ สุปฺปิโยปิ โข ปริพฺพาชโก อนฺตรา จ ราชคหํ อนฺตรา จ นาฬนฺทํ อทฺธานมคฺคปฏิปนฺโน โหติ สทฺธึ อนฺเตวาสินา พฺรหฺมทตฺเตน มาณเวน ฯ ตตฺร สุทํ สุปฺปิโย ปริพฺพาชโก อเนกปริยาเยน พุทฺธสฺส อวณฺณํ ภาสติ ธมฺมสฺส อวณฺณํ ภาสติ สํฆสฺส อวณฺณํ ภาสติ ฯ สุปฺปิยสฺส ปน ปริพฺพาชกสฺส อนฺเตวาสี พฺรหฺมทตฺโต มาณโว อเนกปริยาเยน พุทฺธสฺส วณฺณํ ภาสติ ธมฺมสฺส วณฺณํ ภาสติ สํฆสฺส วณฺณํ ภาสติ ฯ อิติห เต อุโภ อาจริยนฺเตวาสี อญฺญมญฺญสฺส อุชุวิปจฺจนิกวาทา  ภควนฺตํ ปิฏฺฐิโต ปิฏฺฐิโต อนุพนฺธา โหนฺติ ภิกฺขุสํฆญฺจ ฯ

#### จูฬสีลํ
เอวมฺเม สุตํ ฯ เอกํ สมยํ ภควา อนฺตรา จ ราชคหํ อนฺตรา จ นาฬนฺทํ อทฺธานมคฺคปฏิปนฺโน โหติ มหตา ภิกฺขุสํเฆน สทฺธึ ปญฺจมตฺเตหิ ภิกฺขุสเตหิ ฯ สุปฺปิโยปิ โข ปริพฺพาชโก อนฺตรา จ ราชคหํ อนฺตรา จ นาฬนฺทํ อทฺธานมคฺคปฏิปนฺโน โหติ สทฺธึ อนฺเตวาสินา พฺรหฺมทตฺเตน มาณเวน ฯ ตตฺร สุทํ สุปฺปิโย ปริพฺพาชโก อเนกปริยาเยน พุทฺธสฺส อวณฺณํ ภาสติ ธมฺมสฺส อวณฺณํ ภาสติ สํฆสฺส อวณฺณํ ภาสติ ฯ สุปฺปิยสฺส ปน ปริพฺพาชกสฺส อนฺเตวาสี พฺรหฺมทตฺโต มาณโว อเนกปริยาเยน พุทฺธสฺส วณฺณํ ภาสติ ธมฺมสฺส วณฺณํ ภาสติ สํฆสฺส วณฺณํ ภาสติ ฯ อิติห เต อุโภ อาจริยนฺเตวาสี อญฺญมญฺญสฺส อุชุวิปจฺจนิกวาทา  ภควนฺตํ ปิฏฺฐิโต ปิฏฺฐิโต อนุพนฺธา โหนฺติ ภิกฺขุสํฆญฺจ ฯ

#### มชฺฌิมสีลํ
เอวมฺเม สุตํ ฯ เอกํ สมยํ ภควา อนฺตรา จ ราชคหํ อนฺตรา จ นาฬนฺทํ อทฺธานมคฺคปฏิปนฺโน โหติ มหตา ภิกฺขุสํเฆน สทฺธึ ปญฺจมตฺเตหิ ภิกฺขุสเตหิ ฯ สุปฺปิโยปิ โข ปริพฺพาชโก อนฺตรา จ ราชคหํ อนฺตรา จ นาฬนฺทํ อทฺธานมคฺคปฏิปนฺโน โหติ สทฺธึ อนฺเตวาสินา พฺรหฺมทตฺเตน มาณเวน ฯ ตตฺร สุทํ สุปฺปิโย ปริพฺพาชโก อเนกปริยาเยน พุทฺธสฺส อวณฺณํ ภาสติ ธมฺมสฺส อวณฺณํ ภาสติ สํฆสฺส อวณฺณํ ภาสติ ฯ สุปฺปิยสฺส ปน ปริพฺพาชกสฺส อนฺเตวาสี พฺรหฺมทตฺโต มาณโว อเนกปริยาเยน พุทฺธสฺส วณฺณํ ภาสติ ธมฺมสฺส วณฺณํ ภาสติ สํฆสฺส วณฺณํ ภาสติ ฯ อิติห เต อุโภ อาจริยนฺเตวาสี อญฺญมญฺญสฺส อุชุวิปจฺจนิกวาทา  ภควนฺตํ ปิฏฺฐิโต ปิฏฺฐิโต อนุพนฺธา โหนฺติ ภิกฺขุสํฆญฺจ ฯ

#### มหาสีลํ
เอวมฺเม สุตํ ฯ เอกํ สมยํ ภควา อนฺตรา จ ราชคหํ อนฺตรา จ นาฬนฺทํ อทฺธานมคฺคปฏิปนฺโน โหติ มหตา ภิกฺขุสํเฆน สทฺธึ ปญฺจมตฺเตหิ ภิกฺขุสเตหิ ฯ สุปฺปิโยปิ โข ปริพฺพาชโก อนฺตรา จ ราชคหํ อนฺตรา จ นาฬนฺทํ อทฺธานมคฺคปฏิปนฺโน โหติ สทฺธึ อนฺเตวาสินา พฺรหฺมทตฺเตน มาณเวน ฯ ตตฺร สุทํ สุปฺปิโย ปริพฺพาชโก อเนกปริยาเยน พุทฺธสฺส อวณฺณํ ภาสติ ธมฺมสฺส อวณฺณํ ภาสติ สํฆสฺส อวณฺณํ ภาสติ ฯ สุปฺปิยสฺส ปน ปริพฺพาชกสฺส อนฺเตวาสี พฺรหฺมทตฺโต มาณโว อเนกปริยาเยน พุทฺธสฺส วณฺณํ ภาสติ ธมฺมสฺส วณฺณํ ภาสติ สํฆสฺส วณฺณํ ภาสติ ฯ อิติห เต อุโภ อาจริยนฺเตวาสี อญฺญมญฺญสฺส อุชุวิปจฺจนิกวาทา  ภควนฺตํ ปิฏฺฐิโต ปิฏฺฐิโต อนุพนฺธา โหนฺติ ภิกฺขุสํฆญฺจ ฯ

### ทิฐฺฐิ
เอวมฺเม สุตํ ฯ เอกํ สมยํ ภควา อนฺตรา จ ราชคหํ อนฺตรา จ นาฬนฺทํ อทฺธานมคฺคปฏิปนฺโน โหติ มหตา ภิกฺขุสํเฆน สทฺธึ ปญฺจมตฺเตหิ ภิกฺขุสเตหิ ฯ สุปฺปิโยปิ โข ปริพฺพาชโก อนฺตรา จ ราชคหํ อนฺตรา จ นาฬนฺทํ อทฺธานมคฺคปฏิปนฺโน โหติ สทฺธึ อนฺเตวาสินา พฺรหฺมทตฺเตน มาณเวน ฯ ตตฺร สุทํ สุปฺปิโย ปริพฺพาชโก อเนกปริยาเยน พุทฺธสฺส อวณฺณํ ภาสติ ธมฺมสฺส อวณฺณํ ภาสติ สํฆสฺส อวณฺณํ ภาสติ ฯ สุปฺปิยสฺส ปน ปริพฺพาชกสฺส อนฺเตวาสี พฺรหฺมทตฺโต มาณโว อเนกปริยาเยน พุทฺธสฺส วณฺณํ ภาสติ ธมฺมสฺส วณฺณํ ภาสติ สํฆสฺส วณฺณํ ภาสติ ฯ อิติห เต อุโภ อาจริยนฺเตวาสี อญฺญมญฺญสฺส อุชุวิปจฺจนิกวาทา  ภควนฺตํ ปิฏฺฐิโต ปิฏฺฐิโต อนุพนฺธา โหนฺติ ภิกฺขุสํฆญฺจ ฯ

#### ปุพฺพนฺตกปฺปิกา
เอวมฺเม สุตํ ฯ เอกํ สมยํ ภควา อนฺตรา จ ราชคหํ อนฺตรา จ นาฬนฺทํ อทฺธานมคฺคปฏิปนฺโน โหติ มหตา ภิกฺขุสํเฆน สทฺธึ ปญฺจมตฺเตหิ ภิกฺขุสเตหิ ฯ สุปฺปิโยปิ โข ปริพฺพาชโก อนฺตรา จ ราชคหํ อนฺตรา จ นาฬนฺทํ อทฺธานมคฺคปฏิปนฺโน โหติ สทฺธึ อนฺเตวาสินา พฺรหฺมทตฺเตน มาณเวน ฯ ตตฺร สุทํ สุปฺปิโย ปริพฺพาชโก อเนกปริยาเยน พุทฺธสฺส อวณฺณํ ภาสติ ธมฺมสฺส อวณฺณํ ภาสติ สํฆสฺส อวณฺณํ ภาสติ ฯ สุปฺปิยสฺส ปน ปริพฺพาชกสฺส อนฺเตวาสี พฺรหฺมทตฺโต มาณโว อเนกปริยาเยน พุทฺธสฺส วณฺณํ ภาสติ ธมฺมสฺส วณฺณํ ภาสติ สํฆสฺส วณฺณํ ภาสติ ฯ อิติห เต อุโภ อาจริยนฺเตวาสี อญฺญมญฺญสฺส อุชุวิปจฺจนิกวาทา  ภควนฺตํ ปิฏฺฐิโต ปิฏฺฐิโต อนุพนฺธา โหนฺติ ภิกฺขุสํฆญฺจ ฯ

##### สสฺสตวาโท
เอวมฺเม สุตํ ฯ เอกํ สมยํ ภควา อนฺตรา จ ราชคหํ อนฺตรา จ นาฬนฺทํ อทฺธานมคฺคปฏิปนฺโน โหติ มหตา ภิกฺขุสํเฆน สทฺธึ ปญฺจมตฺเตหิ ภิกฺขุสเตหิ ฯ สุปฺปิโยปิ โข ปริพฺพาชโก อนฺตรา จ ราชคหํ อนฺตรา จ นาฬนฺทํ อทฺธานมคฺคปฏิปนฺโน โหติ สทฺธึ อนฺเตวาสินา พฺรหฺมทตฺเตน มาณเวน ฯ ตตฺร สุทํ สุปฺปิโย ปริพฺพาชโก อเนกปริยาเยน พุทฺธสฺส อวณฺณํ ภาสติ ธมฺมสฺส อวณฺณํ ภาสติ สํฆสฺส อวณฺณํ ภาสติ ฯ สุปฺปิยสฺส ปน ปริพฺพาชกสฺส อนฺเตวาสี พฺรหฺมทตฺโต มาณโว อเนกปริยาเยน พุทฺธสฺส วณฺณํ ภาสติ ธมฺมสฺส วณฺณํ ภาสติ สํฆสฺส วณฺณํ ภาสติ ฯ อิติห เต อุโภ อาจริยนฺเตวาสี อญฺญมญฺญสฺส อุชุวิปจฺจนิกวาทา  ภควนฺตํ ปิฏฺฐิโต ปิฏฺฐิโต อนุพนฺธา โหนฺติ ภิกฺขุสํฆญฺจ ฯ

##### เอกจฺจสสฺสตวาโท
เอวมฺเม สุตํ ฯ เอกํ สมยํ ภควา อนฺตรา จ ราชคหํ อนฺตรา จ นาฬนฺทํ อทฺธานมคฺคปฏิปนฺโน โหติ มหตา ภิกฺขุสํเฆน สทฺธึ ปญฺจมตฺเตหิ ภิกฺขุสเตหิ ฯ สุปฺปิโยปิ โข ปริพฺพาชโก อนฺตรา จ ราชคหํ อนฺตรา จ นาฬนฺทํ อทฺธานมคฺคปฏิปนฺโน โหติ สทฺธึ อนฺเตวาสินา พฺรหฺมทตฺเตน มาณเวน ฯ ตตฺร สุทํ สุปฺปิโย ปริพฺพาชโก อเนกปริยาเยน พุทฺธสฺส อวณฺณํ ภาสติ ธมฺมสฺส อวณฺณํ ภาสติ สํฆสฺส อวณฺณํ ภาสติ ฯ สุปฺปิยสฺส ปน ปริพฺพาชกสฺส อนฺเตวาสี พฺรหฺมทตฺโต มาณโว อเนกปริยาเยน พุทฺธสฺส วณฺณํ ภาสติ ธมฺมสฺส วณฺณํ ภาสติ สํฆสฺส วณฺณํ ภาสติ ฯ อิติห เต อุโภ อาจริยนฺเตวาสี อญฺญมญฺญสฺส อุชุวิปจฺจนิกวาทา  ภควนฺตํ ปิฏฺฐิโต ปิฏฺฐิโต อนุพนฺธา โหนฺติ ภิกฺขุสํฆญฺจ ฯ

##### อนฺตานนฺตวาโท
เอวมฺเม สุตํ ฯ เอกํ สมยํ ภควา อนฺตรา จ ราชคหํ อนฺตรา จ นาฬนฺทํ อทฺธานมคฺคปฏิปนฺโน โหติ มหตา ภิกฺขุสํเฆน สทฺธึ ปญฺจมตฺเตหิ ภิกฺขุสเตหิ ฯ สุปฺปิโยปิ โข ปริพฺพาชโก อนฺตรา จ ราชคหํ อนฺตรา จ นาฬนฺทํ อทฺธานมคฺคปฏิปนฺโน โหติ สทฺธึ อนฺเตวาสินา พฺรหฺมทตฺเตน มาณเวน ฯ ตตฺร สุทํ สุปฺปิโย ปริพฺพาชโก อเนกปริยาเยน พุทฺธสฺส อวณฺณํ ภาสติ ธมฺมสฺส อวณฺณํ ภาสติ สํฆสฺส อวณฺณํ ภาสติ ฯ สุปฺปิยสฺส ปน ปริพฺพาชกสฺส อนฺเตวาสี พฺรหฺมทตฺโต มาณโว อเนกปริยาเยน พุทฺธสฺส วณฺณํ ภาสติ ธมฺมสฺส วณฺณํ ภาสติ สํฆสฺส วณฺณํ ภาสติ ฯ อิติห เต อุโภ อาจริยนฺเตวาสี อญฺญมญฺญสฺส อุชุวิปจฺจนิกวาทา  ภควนฺตํ ปิฏฺฐิโต ปิฏฺฐิโต อนุพนฺธา โหนฺติ ภิกฺขุสํฆญฺจ ฯ

##### อมราวิกฺเขปวาโท
เอวมฺเม สุตํ ฯ เอกํ สมยํ ภควา อนฺตรา จ ราชคหํ อนฺตรา จ นาฬนฺทํ อทฺธานมคฺคปฏิปนฺโน โหติ มหตา ภิกฺขุสํเฆน สทฺธึ ปญฺจมตฺเตหิ ภิกฺขุสเตหิ ฯ สุปฺปิโยปิ โข ปริพฺพาชโก อนฺตรา จ ราชคหํ อนฺตรา จ นาฬนฺทํ อทฺธานมคฺคปฏิปนฺโน โหติ สทฺธึ อนฺเตวาสินา พฺรหฺมทตฺเตน มาณเวน ฯ ตตฺร สุทํ สุปฺปิโย ปริพฺพาชโก อเนกปริยาเยน พุทฺธสฺส อวณฺณํ ภาสติ ธมฺมสฺส อวณฺณํ ภาสติ สํฆสฺส อวณฺณํ ภาสติ ฯ สุปฺปิยสฺส ปน ปริพฺพาชกสฺส อนฺเตวาสี พฺรหฺมทตฺโต มาณโว อเนกปริยาเยน พุทฺธสฺส วณฺณํ ภาสติ ธมฺมสฺส วณฺณํ ภาสติ สํฆสฺส วณฺณํ ภาสติ ฯ อิติห เต อุโภ อาจริยนฺเตวาสี อญฺญมญฺญสฺส อุชุวิปจฺจนิกวาทา  ภควนฺตํ ปิฏฺฐิโต ปิฏฺฐิโต อนุพนฺธา โหนฺติ ภิกฺขุสํฆญฺจ ฯ

##### อธิจฺจสมุปฺปนฺนวาโท
เอวมฺเม สุตํ ฯ เอกํ สมยํ ภควา อนฺตรา จ ราชคหํ อนฺตรา จ นาฬนฺทํ อทฺธานมคฺคปฏิปนฺโน โหติ มหตา ภิกฺขุสํเฆน สทฺธึ ปญฺจมตฺเตหิ ภิกฺขุสเตหิ ฯ สุปฺปิโยปิ โข ปริพฺพาชโก อนฺตรา จ ราชคหํ อนฺตรา จ นาฬนฺทํ อทฺธานมคฺคปฏิปนฺโน โหติ สทฺธึ อนฺเตวาสินา พฺรหฺมทตฺเตน มาณเวน ฯ ตตฺร สุทํ สุปฺปิโย ปริพฺพาชโก อเนกปริยาเยน พุทฺธสฺส อวณฺณํ ภาสติ ธมฺมสฺส อวณฺณํ ภาสติ สํฆสฺส อวณฺณํ ภาสติ ฯ สุปฺปิยสฺส ปน ปริพฺพาชกสฺส อนฺเตวาสี พฺรหฺมทตฺโต มาณโว อเนกปริยาเยน พุทฺธสฺส วณฺณํ ภาสติ ธมฺมสฺส วณฺณํ ภาสติ สํฆสฺส วณฺณํ ภาสติ ฯ อิติห เต อุโภ อาจริยนฺเตวาสี อญฺญมญฺญสฺส อุชุวิปจฺจนิกวาทา  ภควนฺตํ ปิฏฺฐิโต ปิฏฺฐิโต อนุพนฺธา โหนฺติ ภิกฺขุสํฆญฺจ ฯ

#### อปรนฺตกปฺปิกา
เอวมฺเม สุตํ ฯ เอกํ สมยํ ภควา อนฺตรา จ ราชคหํ อนฺตรา จ นาฬนฺทํ อทฺธานมคฺคปฏิปนฺโน โหติ มหตา ภิกฺขุสํเฆน สทฺธึ ปญฺจมตฺเตหิ ภิกฺขุสเตหิ ฯ สุปฺปิโยปิ โข ปริพฺพาชโก อนฺตรา จ ราชคหํ อนฺตรา จ นาฬนฺทํ อทฺธานมคฺคปฏิปนฺโน โหติ สทฺธึ อนฺเตวาสินา พฺรหฺมทตฺเตน มาณเวน ฯ ตตฺร สุทํ สุปฺปิโย ปริพฺพาชโก อเนกปริยาเยน พุทฺธสฺส อวณฺณํ ภาสติ ธมฺมสฺส อวณฺณํ ภาสติ สํฆสฺส อวณฺณํ ภาสติ ฯ สุปฺปิยสฺส ปน ปริพฺพาชกสฺส อนฺเตวาสี พฺรหฺมทตฺโต มาณโว อเนกปริยาเยน พุทฺธสฺส วณฺณํ ภาสติ ธมฺมสฺส วณฺณํ ภาสติ สํฆสฺส วณฺณํ ภาสติ ฯ อิติห เต อุโภ อาจริยนฺเตวาสี อญฺญมญฺญสฺส อุชุวิปจฺจนิกวาทา  ภควนฺตํ ปิฏฺฐิโต ปิฏฺฐิโต อนุพนฺธา โหนฺติ ภิกฺขุสํฆญฺจ ฯ

##### สญฺญีวาโท
เอวมฺเม สุตํ ฯ เอกํ สมยํ ภควา อนฺตรา จ ราชคหํ อนฺตรา จ นาฬนฺทํ อทฺธานมคฺคปฏิปนฺโน โหติ มหตา ภิกฺขุสํเฆน สทฺธึ ปญฺจมตฺเตหิ ภิกฺขุสเตหิ ฯ สุปฺปิโยปิ โข ปริพฺพาชโก อนฺตรา จ ราชคหํ อนฺตรา จ นาฬนฺทํ อทฺธานมคฺคปฏิปนฺโน โหติ สทฺธึ อนฺเตวาสินา พฺรหฺมทตฺเตน มาณเวน ฯ ตตฺร สุทํ สุปฺปิโย ปริพฺพาชโก อเนกปริยาเยน พุทฺธสฺส อวณฺณํ ภาสติ ธมฺมสฺส อวณฺณํ ภาสติ สํฆสฺส อวณฺณํ ภาสติ ฯ สุปฺปิยสฺส ปน ปริพฺพาชกสฺส อนฺเตวาสี พฺรหฺมทตฺโต มาณโว อเนกปริยาเยน พุทฺธสฺส วณฺณํ ภาสติ ธมฺมสฺส วณฺณํ ภาสติ สํฆสฺส วณฺณํ ภาสติ ฯ อิติห เต อุโภ อาจริยนฺเตวาสี อญฺญมญฺญสฺส อุชุวิปจฺจนิกวาทา  ภควนฺตํ ปิฏฺฐิโต ปิฏฺฐิโต อนุพนฺธา โหนฺติ ภิกฺขุสํฆญฺจ ฯ

##### อสญฺญีวาโท
เอวมฺเม สุตํ ฯ เอกํ สมยํ ภควา อนฺตรา จ ราชคหํ อนฺตรา จ นาฬนฺทํ อทฺธานมคฺคปฏิปนฺโน โหติ มหตา ภิกฺขุสํเฆน สทฺธึ ปญฺจมตฺเตหิ ภิกฺขุสเตหิ ฯ สุปฺปิโยปิ โข ปริพฺพาชโก อนฺตรา จ ราชคหํ อนฺตรา จ นาฬนฺทํ อทฺธานมคฺคปฏิปนฺโน โหติ สทฺธึ อนฺเตวาสินา พฺรหฺมทตฺเตน มาณเวน ฯ ตตฺร สุทํ สุปฺปิโย ปริพฺพาชโก อเนกปริยาเยน พุทฺธสฺส อวณฺณํ ภาสติ ธมฺมสฺส อวณฺณํ ภาสติ สํฆสฺส อวณฺณํ ภาสติ ฯ สุปฺปิยสฺส ปน ปริพฺพาชกสฺส อนฺเตวาสี พฺรหฺมทตฺโต มาณโว อเนกปริยาเยน พุทฺธสฺส วณฺณํ ภาสติ ธมฺมสฺส วณฺณํ ภาสติ สํฆสฺส วณฺณํ ภาสติ ฯ อิติห เต อุโภ อาจริยนฺเตวาสี อญฺญมญฺญสฺส อุชุวิปจฺจนิกวาทา  ภควนฺตํ ปิฏฺฐิโต ปิฏฺฐิโต อนุพนฺธา โหนฺติ ภิกฺขุสํฆญฺจ ฯ

##### เนวสญฺญีนาสญฺญีวาโท
เอวมฺเม สุตํ ฯ เอกํ สมยํ ภควา อนฺตรา จ ราชคหํ อนฺตรา จ นาฬนฺทํ อทฺธานมคฺคปฏิปนฺโน โหติ มหตา ภิกฺขุสํเฆน สทฺธึ ปญฺจมตฺเตหิ ภิกฺขุสเตหิ ฯ สุปฺปิโยปิ โข ปริพฺพาชโก อนฺตรา จ ราชคหํ อนฺตรา จ นาฬนฺทํ อทฺธานมคฺคปฏิปนฺโน โหติ สทฺธึ อนฺเตวาสินา พฺรหฺมทตฺเตน มาณเวน ฯ ตตฺร สุทํ สุปฺปิโย ปริพฺพาชโก อเนกปริยาเยน พุทฺธสฺส อวณฺณํ ภาสติ ธมฺมสฺส อวณฺณํ ภาสติ สํฆสฺส อวณฺณํ ภาสติ ฯ สุปฺปิยสฺส ปน ปริพฺพาชกสฺส อนฺเตวาสี พฺรหฺมทตฺโต มาณโว อเนกปริยาเยน พุทฺธสฺส วณฺณํ ภาสติ ธมฺมสฺส วณฺณํ ภาสติ สํฆสฺส วณฺณํ ภาสติ ฯ อิติห เต อุโภ อาจริยนฺเตวาสี อญฺญมญฺญสฺส อุชุวิปจฺจนิกวาทา  ภควนฺตํ ปิฏฺฐิโต ปิฏฺฐิโต อนุพนฺธา โหนฺติ ภิกฺขุสํฆญฺจ ฯ

##### อุจฺเฉทวาโท
เอวมฺเม สุตํ ฯ เอกํ สมยํ ภควา อนฺตรา จ ราชคหํ อนฺตรา จ นาฬนฺทํ อทฺธานมคฺคปฏิปนฺโน โหติ มหตา ภิกฺขุสํเฆน สทฺธึ ปญฺจมตฺเตหิ ภิกฺขุสเตหิ ฯ สุปฺปิโยปิ โข ปริพฺพาชโก อนฺตรา จ ราชคหํ อนฺตรา จ นาฬนฺทํ อทฺธานมคฺคปฏิปนฺโน โหติ สทฺธึ อนฺเตวาสินา พฺรหฺมทตฺเตน มาณเวน ฯ ตตฺร สุทํ สุปฺปิโย ปริพฺพาชโก อเนกปริยาเยน พุทฺธสฺส อวณฺณํ ภาสติ ธมฺมสฺส อวณฺณํ ภาสติ สํฆสฺส อวณฺณํ ภาสติ ฯ สุปฺปิยสฺส ปน ปริพฺพาชกสฺส อนฺเตวาสี พฺรหฺมทตฺโต มาณโว อเนกปริยาเยน พุทฺธสฺส วณฺณํ ภาสติ ธมฺมสฺส วณฺณํ ภาสติ สํฆสฺส วณฺณํ ภาสติ ฯ อิติห เต อุโภ อาจริยนฺเตวาสี อญฺญมญฺญสฺส อุชุวิปจฺจนิกวาทา  ภควนฺตํ ปิฏฺฐิโต ปิฏฺฐิโต อนุพนฺธา โหนฺติ ภิกฺขุสํฆญฺจ ฯ

##### ทิฏฺฐธมฺมนิพฺพานวาโท
เอวมฺเม สุตํ ฯ เอกํ สมยํ ภควา อนฺตรา จ ราชคหํ อนฺตรา จ นาฬนฺทํ อทฺธานมคฺคปฏิปนฺโน โหติ มหตา ภิกฺขุสํเฆน สทฺธึ ปญฺจมตฺเตหิ ภิกฺขุสเตหิ ฯ สุปฺปิโยปิ โข ปริพฺพาชโก อนฺตรา จ ราชคหํ อนฺตรา จ นาฬนฺทํ อทฺธานมคฺคปฏิปนฺโน โหติ สทฺธึ อนฺเตวาสินา พฺรหฺมทตฺเตน มาณเวน ฯ ตตฺร สุทํ สุปฺปิโย ปริพฺพาชโก อเนกปริยาเยน พุทฺธสฺส อวณฺณํ ภาสติ ธมฺมสฺส อวณฺณํ ภาสติ สํฆสฺส อวณฺณํ ภาสติ ฯ สุปฺปิยสฺส ปน ปริพฺพาชกสฺส อนฺเตวาสี พฺรหฺมทตฺโต มาณโว อเนกปริยาเยน พุทฺธสฺส วณฺณํ ภาสติ ธมฺมสฺส วณฺณํ ภาสติ สํฆสฺส วณฺณํ ภาสติ ฯ อิติห เต อุโภ อาจริยนฺเตวาสี อญฺญมญฺญสฺส อุชุวิปจฺจนิกวาทา  ภควนฺตํ ปิฏฺฐิโต ปิฏฺฐิโต อนุพนฺธา โหนฺติ ภิกฺขุสํฆญฺจ ฯ

### อตฺตาโลกปญฺญตฺติวตฺถุ
เอวมฺเม สุตํ ฯ เอกํ สมยํ ภควา อนฺตรา จ ราชคหํ อนฺตรา จ นาฬนฺทํ อทฺธานมคฺคปฏิปนฺโน โหติ มหตา ภิกฺขุสํเฆน สทฺธึ ปญฺจมตฺเตหิ ภิกฺขุสเตหิ ฯ สุปฺปิโยปิ โข ปริพฺพาชโก อนฺตรา จ ราชคหํ อนฺตรา จ นาฬนฺทํ อทฺธานมคฺคปฏิปนฺโน โหติ สทฺธึ อนฺเตวาสินา พฺรหฺมทตฺเตน มาณเวน ฯ ตตฺร สุทํ สุปฺปิโย ปริพฺพาชโก อเนกปริยาเยน พุทฺธสฺส อวณฺณํ ภาสติ ธมฺมสฺส อวณฺณํ ภาสติ สํฆสฺส อวณฺณํ ภาสติ ฯ สุปฺปิยสฺส ปน ปริพฺพาชกสฺส อนฺเตวาสี พฺรหฺมทตฺโต มาณโว อเนกปริยาเยน พุทฺธสฺส วณฺณํ ภาสติ ธมฺมสฺส วณฺณํ ภาสติ สํฆสฺส วณฺณํ ภาสติ ฯ อิติห เต อุโภ อาจริยนฺเตวาสี อญฺญมญฺญสฺส อุชุวิปจฺจนิกวาทา  ภควนฺตํ ปิฏฺฐิโต ปิฏฺฐิโต อนุพนฺธา โหนฺติ ภิกฺขุสํฆญฺจ ฯ

#### ปริตสฺสิตวิปฺผนฺทิตวาโร
เอวมฺเม สุตํ ฯ เอกํ สมยํ ภควา อนฺตรา จ ราชคหํ อนฺตรา จ นาฬนฺทํ อทฺธานมคฺคปฏิปนฺโน โหติ มหตา ภิกฺขุสํเฆน สทฺธึ ปญฺจมตฺเตหิ ภิกฺขุสเตหิ ฯ สุปฺปิโยปิ โข ปริพฺพาชโก อนฺตรา จ ราชคหํ อนฺตรา จ นาฬนฺทํ อทฺธานมคฺคปฏิปนฺโน โหติ สทฺธึ อนฺเตวาสินา พฺรหฺมทตฺเตน มาณเวน ฯ ตตฺร สุทํ สุปฺปิโย ปริพฺพาชโก อเนกปริยาเยน พุทฺธสฺส อวณฺณํ ภาสติ ธมฺมสฺส อวณฺณํ ภาสติ สํฆสฺส อวณฺณํ ภาสติ ฯ สุปฺปิยสฺส ปน ปริพฺพาชกสฺส อนฺเตวาสี พฺรหฺมทตฺโต มาณโว อเนกปริยาเยน พุทฺธสฺส วณฺณํ ภาสติ ธมฺมสฺส วณฺณํ ภาสติ สํฆสฺส วณฺณํ ภาสติ ฯ อิติห เต อุโภ อาจริยนฺเตวาสี อญฺญมญฺญสฺส อุชุวิปจฺจนิกวาทา  ภควนฺตํ ปิฏฺฐิโต ปิฏฺฐิโต อนุพนฺธา โหนฺติ ภิกฺขุสํฆญฺจ ฯ

#### ผสฺสปจฺจยาวาโร
เอวมฺเม สุตํ ฯ เอกํ สมยํ ภควา อนฺตรา จ ราชคหํ อนฺตรา จ นาฬนฺทํ อทฺธานมคฺคปฏิปนฺโน โหติ มหตา ภิกฺขุสํเฆน สทฺธึ ปญฺจมตฺเตหิ ภิกฺขุสเตหิ ฯ สุปฺปิโยปิ โข ปริพฺพาชโก อนฺตรา จ ราชคหํ อนฺตรา จ นาฬนฺทํ อทฺธานมคฺคปฏิปนฺโน โหติ สทฺธึ อนฺเตวาสินา พฺรหฺมทตฺเตน มาณเวน ฯ ตตฺร สุทํ สุปฺปิโย ปริพฺพาชโก อเนกปริยาเยน พุทฺธสฺส อวณฺณํ ภาสติ ธมฺมสฺส อวณฺณํ ภาสติ สํฆสฺส อวณฺณํ ภาสติ ฯ สุปฺปิยสฺส ปน ปริพฺพาชกสฺส อนฺเตวาสี พฺรหฺมทตฺโต มาณโว อเนกปริยาเยน พุทฺธสฺส วณฺณํ ภาสติ ธมฺมสฺส วณฺณํ ภาสติ สํฆสฺส วณฺณํ ภาสติ ฯ อิติห เต อุโภ อาจริยนฺเตวาสี อญฺญมญฺญสฺส อุชุวิปจฺจนิกวาทา  ภควนฺตํ ปิฏฺฐิโต ปิฏฺฐิโต อนุพนฺธา โหนฺติ ภิกฺขุสํฆญฺจ ฯ

#### เนตํ ฐานํ วิชฺชติวาโร
เอวมฺเม สุตํ ฯ เอกํ สมยํ ภควา อนฺตรา จ ราชคหํ อนฺตรา จ นาฬนฺทํ อทฺธานมคฺคปฏิปนฺโน โหติ มหตา ภิกฺขุสํเฆน สทฺธึ ปญฺจมตฺเตหิ ภิกฺขุสเตหิ ฯ สุปฺปิโยปิ โข ปริพฺพาชโก อนฺตรา จ ราชคหํ อนฺตรา จ นาฬนฺทํ อทฺธานมคฺคปฏิปนฺโน โหติ สทฺธึ อนฺเตวาสินา พฺรหฺมทตฺเตน มาณเวน ฯ ตตฺร สุทํ สุปฺปิโย ปริพฺพาชโก อเนกปริยาเยน พุทฺธสฺส อวณฺณํ ภาสติ ธมฺมสฺส อวณฺณํ ภาสติ สํฆสฺส อวณฺณํ ภาสติ ฯ สุปฺปิยสฺส ปน ปริพฺพาชกสฺส อนฺเตวาสี พฺรหฺมทตฺโต มาณโว อเนกปริยาเยน พุทฺธสฺส วณฺณํ ภาสติ ธมฺมสฺส วณฺณํ ภาสติ สํฆสฺส วณฺณํ ภาสติ ฯ อิติห เต อุโภ อาจริยนฺเตวาสี อญฺญมญฺญสฺส อุชุวิปจฺจนิกวาทา  ภควนฺตํ ปิฏฺฐิโต ปิฏฺฐิโต อนุพนฺธา โหนฺติ ภิกฺขุสํฆญฺจ ฯ

#### ทิฏฺิฐคติกาธิฏฺฐานวฏฺฏกถา
เอวมฺเม สุตํ ฯ เอกํ สมยํ ภควา อนฺตรา จ ราชคหํ อนฺตรา จ นาฬนฺทํ อทฺธานมคฺคปฏิปนฺโน โหติ มหตา ภิกฺขุสํเฆน สทฺธึ ปญฺจมตฺเตหิ ภิกฺขุสเตหิ ฯ สุปฺปิโยปิ โข ปริพฺพาชโก อนฺตรา จ ราชคหํ อนฺตรา จ นาฬนฺทํ อทฺธานมคฺคปฏิปนฺโน โหติ สทฺธึ อนฺเตวาสินา พฺรหฺมทตฺเตน มาณเวน ฯ ตตฺร สุทํ สุปฺปิโย ปริพฺพาชโก อเนกปริยาเยน พุทฺธสฺส อวณฺณํ ภาสติ ธมฺมสฺส อวณฺณํ ภาสติ สํฆสฺส อวณฺณํ ภาสติ ฯ สุปฺปิยสฺส ปน ปริพฺพาชกสฺส อนฺเตวาสี พฺรหฺมทตฺโต มาณโว อเนกปริยาเยน พุทฺธสฺส วณฺณํ ภาสติ ธมฺมสฺส วณฺณํ ภาสติ สํฆสฺส วณฺณํ ภาสติ ฯ อิติห เต อุโภ อาจริยนฺเตวาสี อญฺญมญฺญสฺส อุชุวิปจฺจนิกวาทา  ภควนฺตํ ปิฏฺฐิโต ปิฏฺฐิโต อนุพนฺธา โหนฺติ ภิกฺขุสํฆญฺจ ฯ
